# Python stubs generated by omniidl from idl/crane_control.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "_GlobalIDL"
#
__name__ = "_GlobalIDL"
_0__GlobalIDL = omniORB.openModule("_GlobalIDL", r"idl/crane_control.idl")
_0__GlobalIDL__POA = omniORB.openModule("_GlobalIDL__POA", r"idl/crane_control.idl")


# interface CraneArmService
_0__GlobalIDL._d_CraneArmService = (omniORB.tcInternal.tv_objref, "IDL:CraneArmService:1.0", "CraneArmService")
omniORB.typeMapping["IDL:CraneArmService:1.0"] = _0__GlobalIDL._d_CraneArmService
_0__GlobalIDL.CraneArmService = omniORB.newEmptyClass()
class CraneArmService :
    _NP_RepositoryId = _0__GlobalIDL._d_CraneArmService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0__GlobalIDL.CraneArmService = CraneArmService
_0__GlobalIDL._tc_CraneArmService = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_CraneArmService)
omniORB.registerType(CraneArmService._NP_RepositoryId, _0__GlobalIDL._d_CraneArmService, _0__GlobalIDL._tc_CraneArmService)

# CraneArmService operations and attributes
CraneArmService._d_strike = ((omniORB.tcInternal.tv_double, ), (omniORB.tcInternal.tv_boolean, ), None)
CraneArmService._d_goHome = ((), (omniORB.tcInternal.tv_boolean, ), None)
CraneArmService._d_celebrate = ((), (omniORB.tcInternal.tv_boolean, ), None)

# CraneArmService object reference
class _objref_CraneArmService (CORBA.Object):
    _NP_RepositoryId = CraneArmService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def strike(self, *args):
        return self._obj.invoke("strike", _0__GlobalIDL.CraneArmService._d_strike, args)

    def goHome(self, *args):
        return self._obj.invoke("goHome", _0__GlobalIDL.CraneArmService._d_goHome, args)

    def celebrate(self, *args):
        return self._obj.invoke("celebrate", _0__GlobalIDL.CraneArmService._d_celebrate, args)

omniORB.registerObjref(CraneArmService._NP_RepositoryId, _objref_CraneArmService)
_0__GlobalIDL._objref_CraneArmService = _objref_CraneArmService
del CraneArmService, _objref_CraneArmService

# CraneArmService skeleton
__name__ = "_GlobalIDL__POA"
class CraneArmService (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.CraneArmService._NP_RepositoryId


    _omni_op_d = {"strike": _0__GlobalIDL.CraneArmService._d_strike, "goHome": _0__GlobalIDL.CraneArmService._d_goHome, "celebrate": _0__GlobalIDL.CraneArmService._d_celebrate}

CraneArmService._omni_skeleton = CraneArmService
_0__GlobalIDL__POA.CraneArmService = CraneArmService
omniORB.registerSkeleton(CraneArmService._NP_RepositoryId, CraneArmService)
del CraneArmService
__name__ = "_GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "crane_control_idl"

_exported_modules = ( "_GlobalIDL", )

# The end.
